### ISSUE TITLE
Come superare il problema dei link.md

### ISSUE THREAD

**Issue by pigreco** [pigreco/HfcQGIS#15]
piccolo quadro sinottico (idea geniale di @gbvitrano)
1. all'interno di ogni gruppo funzioni duplicare il file README.md → readme_mod.md;
2. in ogni readme_mod.md modificare tutti i link da [link.md] → [link.html];
3. creare un file index.rst nella root che punti ad un file index,rst nella cartella **gr_funzioni**;
4. nella cartella **gr_funzioni**: index.rst punta verso i file readme_mod di tutte le funzioni;

**Comment by aborruso** [comment]
A me la cosa non convince, perché c'è da scrivere due volte tutto e gli errori umani potrebbero essere tanti.

Io sono per usare questo repo solo come source della documentazione, quindi non come spazio in cui leggere, ma solo come spazio sorgente del sito ufficiale.

**Comment by gbvitrano** [comment]
Capisco che Totò voglia lasciare integro il suo mega lavoro, con questo piccolo trucco salviamo capre e cavoli.
Tanto ancora siamo in una fase beta a lui la scelta finale.

**Comment by pigreco** [comment]
@aborruso @gbvitrano 
le cose più semplici sono sempre le migliori,
Andy ha ragione, duplicare i file comporta un rischio di errori e un doppio lavoro.

Per me **nullaosta**, possiamo procedere al cambio di estensione per tutti i link (da .md →.html)
sempre che siamo tutti consci su quello che comporta (io lo sono)
