### ISSUE TITLE
un file sospetto ahahah

### ISSUE THREAD

**Issue by pigreco** [pigreco/HfcQGIS#16]
questo [file](https://github.com/pigreco/HfcQGIS/blob/master/gr_funzioni/geometria/funzioni/expression_geometry_qgis216.md) è l'elenco delle funzioni del gruppo **geometry** nella versione **QGIS 2.16**

NON ha nessuna funzione se non quella di ricordare quali e quanti funzioni aveva la 2.16

grazie per la segnalazione @aborruso

**Comment by aborruso** [comment]
Caro @pigreco tutti i file md contenuti nel repo, alimenteranno l'e-book. Quindi questo strano file apparirà tra i risultati del search, e sarà sfogliabile.

Se non ti serve solo come promemoria personale, gli cambierei l'estensione in txt. Se ti serve che rimanga in formato md, ci studiamo come escludere in sphinx certi file.

**Comment by pigreco** [comment]
> Caro @pigreco tutti i file md contenuti nel repo, alimenteranno l'e-book.

Giusta osservazione, ho cambiato l'estensione del file in .txt
 ecco il [file ](https://github.com/pigreco/HfcQGIS/blob/master/gr_funzioni/geometria/funzioni/expression_geometry_qgis216.txt)rinominato
