### ISSUE TITLE
andare indietro nel tempo

### ISSUE THREAD

**Issue by pigreco** [pigreco/HfcQGIS#22]
@aborruso 
appena puoi riporti questo repo a questo commit
https://github.com/pigreco/HfcQGIS/tree/8238caf986e91cbe2db185beea2a327c6b47ca25

ho fatto mille prove, ho usato git shell, niente non riesco a riportare il repo indietro.

grazie

**Comment by aborruso** [comment]
```
git rm -r .
git checkout  8238caf986e91cbe2db185beea2a327c6b47ca25 .
git commit -am "tornato indietro a 8238caf986e91cbe2db185beea2a327c6b47ca25"
git push
```

Fonte https://stackoverflow.com/questions/4114095/how-to-revert-a-git-repository-to-a-previous-commit
